enableSodiumMenu = true
cloudCulling = true
signTextCulling = true
rainCulling = true
useBlockStateCulling = true
useCustomItemFrameRenderer = true
itemFrameMapCulling = true
useItemFrameLOD = true
itemFrameLODRange = 384
useItemFrame3FaceCulling = true
itemFrame3FaceCullingRange = 12.0
leavesCullingMode = "DEFAULT"
leavesCullingAmount = 2
includeMangroveRoots = true
powderSnowCulling = true
entityModelCulling = false
useOnModdedBlocksByDefault = true

[modCompatibility]
universal_ores = true
varietyaquatic = true
supplementaries = true
colourfulllamas = true
fishofthieves = true
barteringstation = true
grassoverhaul = true
mbt = true
croptopia = true
promenade = true
geodes = true
colourfulgoats = true
connectedglass = true
friendsandfoes = true
additionallanterns = true
woof = true
twigs = true
fwaystones = true
minecraft = true
philipsruins = true
swampier_swamps = true
comforts = true
stoneworks = true
enhancedcelestials = true
duckling = true
snowyspirit = true
betterarcheology = true
tradingpost = true
creeperoverhaul = true
goated = true
handcrafted = true
traverse = true
snowrealmagic = true
moyai = true
frostiful = true
creatures_from_the_snow = true
rare-ice = true
carpeted = true
betterlily = true
rechiseled = true
blockus = true
